services:
  _defaults:
    autowire: true
    autoconfigure: true

  con4gis\IOTravelCostsBundle\Controller\TravelCostsController:
    class: con4gis\IOTravelCostsBundle\Controller\TravelCostsController
    autowire: true
    public: true
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@event_dispatcher"
      - "@contao.framework"